formatter: "markdown" # this is required

version: "v0.16.0"

header-from: main.tf

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Module Overview

  The detailed information about the module.

  {{ .Providers }}

  The module automatically inherits default provider configurations from its parent.

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: false
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
