version: 1
frontend:
  phases:
    preBuild:
      commands:
        - cd amplify-app/amplifyapp
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files: "**/*"
  cache:
    paths:
      - node_modules/**/*
