---
AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This Cloudformation template creates an S3 bucket and bucket policy suitable
  for a Terraform S3 State Backend. https://github.com/thoughtbot/cloudformation-terraform-state-backend

Parameters:
  KMSKeyAlias:
    Description: The KMS key alias for bucket encryption
    Default: aws/s3
    Type: String
  IAMUser:
    Description: The IAM user name that grant access to the bucket
    Default: app-deployer
    Type: String
  IAMRole:
    Description: The IAM role name that grant access to the bucket
    Default: GitHubAction-AssumeRoleWithAction
    Type: String
  IAMRootUser:
    Description: The IAM role name that grant access to the bucket
    Default: camille
    Type: String

Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref KMSKeyAlias
      BucketName: !Sub terraform-state-${AWS::AccountId}-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled

  StateBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Bucket: !Ref StateBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowUserAccessToBucket
            Effect: Allow
            Action: s3:*
            Resource:
              - !Sub ${StateBucket.Arn}/*
              - !Sub ${StateBucket.Arn}
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/${IAMRootUser}
                - !Sub arn:aws:iam::${AWS::AccountId}:user/${IAMUser}
                - !Sub arn:aws:iam::${AWS::AccountId}:role/${IAMRole}

Outputs:
  StateBucketName:
    Description: Name of the S3 bucket containing Terraform state
    Value: !Ref StateBucket
