name: EC2 Instance Apply

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: Environment to run agains
        type: choice
        options:
          - dev
          - prod
        default: dev
        required: true
      destroy:
        description: True to destroy
        required: true
        default: false
        type: boolean

run-name: ${{ format('Deploy to {0} (destroy = {1})', inputs.environment, inputs.destroy) }}

permissions:
  contents: read
  pull-requests: write

jobs:
  deploy:
    if: ${{ inputs.destroy == false }}
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-deploy-reusable.yaml@main
    with:
      environment: ${{ inputs.environment }}
      nickname: ec2instance
      working-directory: ec2-instance
      tf-version: 1.4.2
  destroy:
    if: ${{ inputs.destroy == true }}
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-destroy-reusable.yaml@main
    with:
      environment: ${{ inputs.environment }}
      nickname: ec2instance
      working-directory: ec2-instance
      tf-version: 1.4.2
