name: Secret Manager Apply

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: Environment to run against
        type: choice
        options:
          - prod
        default: prod
        required: true
      destroy:
        description: True to destroy
        required: true
        default: false
        type: boolean

run-name: ${{ format('Deploy to {0} (destroy = {1})', inputs.environment, inputs.destroy) }}

permissions:
  contents: read
  pull-requests: write

env:
  # Terraform Variables are prefixed with TF_VAR
  TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  TF_VAR_database_password: ${{ secrets.TF_VAR_DATABASE_PASSWORD }}

jobs:
  deploy:
    if: ${{ inputs.destroy == false }}
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-deploy-reusable.yaml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      nickname: secretmanager
      working-directory: secret-manager
  destroy:
    if: ${{ inputs.destroy == true }}
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-destroy-reusable.yaml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      nickname: secretmanager
      working-directory: secret-manager
