name: SG Rules Apply

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: Environment to run against
        type: choice
        options:
          - prod
        default: prod
        required: true
      destroy:
        description: True to destroy
        required: true
        default: false
        type: boolean

run-name: Deploy to ${{ inputs.environment }} with destroy = ${{ inputs.destroy }}

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  plan:
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-plan-reusable.yaml@main
    secrets: inherit
    with:
      destroy: ${{ inputs.destroy }}
      environment: ${{ inputs.environment }}
      nickname: sg-rules
      working-directory: sg-rules

  apply:
    needs: [plan]
    if: ${{ needs.plan.outputs.exitcode == 2 }}
    uses: camillehe1992/reusable-workflows/.github/workflows/terraform-apply-reusable.yaml@main
    secrets: inherit
    with:
      environment: ${{ inputs.environment }}
      nickname: sg-rules
      working-directory: sg-rules
